name             'mailcatcher'
maintainer       'Hirotaka Kato'
maintainer_email 'HirotakaKato@users.noreply.github.com'
license          'MIT'
description      'Installs/Configures MailCatcher'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.5.12'
supports         'centos'
depends          'iptables'
depends          'postfix'
