name             'php'
maintainer       'Hirotaka Kato'
maintainer_email 'HirotakaKato@users.noreply.github.com'
license          'MIT'
description      'Installs/Configures PHP'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '5.5'
supports         'centos'
depends          'httpd'
depends          'mysqld'
