#!/bin/sh

# chkconfig:   2345 79 31
# description: mailcatcher

# Source function library.
. /etc/rc.d/init.d/functions

prog=mailcatcher
pidfile=/var/run/$prog.pid

start()
{
	[ -s $pidfile ] && ps -p `cat $pidfile` > /dev/null && return 2
	echo -n $"Starting $prog: "
	sudo -u nobody mailcatcher -f --http-ip=0.0.0.0 > /var/log/$prog.log 2>&1 &
	RETVAL=$?
	[ $RETVAL -eq 0 ] && echo $! > $pidfile
	[ $RETVAL -eq 0 ] && success || failure
	echo
	return $RETVAL
}

stop()
{
	[ -s $pidfile ] || return 2
	echo -n $"Stopping $prog: "
	killproc -p $pidfile $prog
	RETVAL=$?
	[ $RETVAL -eq 0 ] && rm -f $pidfile
	echo
	return $RETVAL
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	status)
		status -p $pidfile $prog
		;;
	*)
		echo $"Usage: $0 {start|stop|restart|status}"
		exit 2
esac

exit $?
